### Python with Numpy and Pandas
* Python is very efficient
* Numpy adds arrays
* Pandas adds dataframes

In [1]:
import numpy as np
import pandas as pd

In [2]:
# one-dimensional arrays
a = np.array( [5, 72, 13, 100] )
b = np.array( [2, 5, 10, 30] )

result = np.multiply(a, b)
result

array([  10,  360,  130, 3000])

In [3]:
# matrices
matrix_a = np.array([[1,2],[3,4]])
matrix_b = np.array([[.5,.6],[.7,.8]])

result = matrix_a * matrix_b
result.T # T will transpose the matrix

array([[0.5, 2.1],
       [1.2, 3.2]])

In [4]:
# we may flatten the matrix
result.flatten()

array([0.5, 1.2, 2.1, 3.2])

### Working with Data Structures

In [5]:
# Numpy can generate random values
f = np.random.normal(10, 3, 10**7) # sd 3 mean 10, sample size 8
f
f.mean()
f.max()

np.float64(25.26514309271886)

### Loading External Data

In [6]:
# we may choose to parse the dates
sp500 = pd.read_csv('StockData/sp500.csv', parse_dates=True, date_format='%m/%d%y')
# sp500 = pd.read_csv('StockData/sp500.csv')
# sp500 = pd.read_csv('https://raw.githubusercontent.com/onionmccabbage/pythonThuFri2026/refs/heads/main/StockData/SP500.csv')
# type(sp500)
sp500['Date'] = pd.to_datetime( sp500['Date'], format='%m/%d/%y' )
# the date must match the incoming data e.g. '%Y-%m-%d'
sp500

,Date,Open,High,Low,Close,Adj Close,Volume
0,2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
1,2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2,2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
3,2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
4,2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
...,...,...,...,...,...,...,...
1255,2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000
1256,2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000
1257,2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000
1258,2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
1259,2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000

In [7]:
sp500.describe()

,Date,Open,High,Low,Close,Adj Close,Volume
count,1260,1260.000000,1260.000000,1260.000000,1260.000000,1260.000000,1.260000e+03
mean,2016-03-30 09:57:42.857142,2208.119022,2217.222041,2198.329731,2208.579183,2208.579183,3.545683e+09
min,2013-09-30 00:00:00,1656.989990,1662.469971,1646.469971,1655.449951,1655.449951,1.307630e+09
25%,2014-12-29 18:00:00,1984.504975,1991.565002,1975.112457,1985.515015,1985.515015,3.154532e+09
50%,2016-03-31 12:00:00,2101.550049,2108.744995,2091.594971,2101.265014,2101.265014,3.448470e+09
75%,2017-06-29 06:00:00,2434.364991,2441.522522,2428.234985,2434.777527,2434.777527,3.821982e+09
max,2018-09-28 00:00:00,2936.760010,2940.909912,2927.110107,2930.750000,2930.750000,7.597450e+09
std,NaN,311.783587,312.018261,311.768926,311.699505,311.699505,6.785854e+08

In [8]:
# we may use slicing to access parts of the data
sp500.iloc[0:12] # iloc means index location

,Date,Open,High,Low,Close,Adj Close,Volume
0,2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
1,2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2,2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
3,2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
4,2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
5,2013-10-07,1687.150024,1687.150024,1674.699951,1676.119995,1676.119995,2678490000
6,2013-10-08,1676.219971,1676.790039,1655.030029,1655.449951,1655.449951,3569230000
7,2013-10-09,1656.989990,1662.469971,1646.469971,1656.400024,1656.400024,3577840000
8,2013-10-10,1660.880005,1692.560059,1660.880005,1692.560059,1692.560059,3362300000
9,2013-10-11,1691.089966,1703.439941,1688.520020,1703.199951,1703.199951,2944670000
10,2013-10-14,1699.859985,1711.030029,1692.130005,1710.140015,1710.140015,2580580000
11,2013-10-15,1709.170044,1711.569946,1695.930054,1698.060059,1698.060059,3327740000

In [9]:
# Dates etc.
sp500.info()

<class 'pandas.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1260 non-null   datetime64[us]
 1   Open       1260 non-null   float64
 2   High       1260 non-null   float64
 3   Low        1260 non-null   float64
 4   Close      1260 non-null   float64
 5   Adj Close  1260 non-null   float64
 6   Volume     1260 non-null   int64
dtypes: datetime64[us](1), float64(5), int64(1)
memory usage: 69.0 KB

In [10]:
sp500.head(3)

,Date,Open,High,Low,Close,Adj Close,Volume
0,2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
1,2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2,2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000

### Slicing and working with columns
Index, iloc and also loc

In [ ]:
# we often need to use existing data as an index
# specify an existing column
# sp500.set_index( 'Date' ) # NB this does not persist (by design)
sp500.set_index( 'Date', inplace=True) # here we do persist the change (we lose the original structure)

In [23]:
# sp500
# we know about iloc()
sp500.iloc[300:801] # even though the index is 'Date'
# there is still an underlying ordinal index 0, 1, 2 etc

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2014-12-08,2074.840088,2075.780029,2054.270020,2060.310059,2060.310059,3800990000
2014-12-09,2056.550049,2060.600098,2034.170044,2059.820068,2059.820068,3970150000
2014-12-10,2058.860107,2058.860107,2024.260010,2026.140015,2026.140015,4114440000
2014-12-11,2027.920044,2055.530029,2027.920044,2035.329956,2035.329956,3917950000
2014-12-12,2030.359985,2032.250000,2002.329956,2002.329956,2002.329956,4157650000
...,...,...,...,...,...,...
2016-11-25,2206.270020,2213.350098,2206.270020,2213.350098,2213.350098,1584600000
2016-11-28,2210.209961,2211.139893,2200.360107,2201.719971,2201.719971,3505650000
2016-11-29,2200.760010,2210.459961,2198.149902,2204.659912,2204.659912,3706560000
2016-11-30,2204.969971,2214.100098,2198.810059,2198.810059,2198.810059,5533980000
2016-12-01,2200.169922,2202.600098,2187.439941,2191.080078,2191.080078,5063740000

In [25]:
# the ONE exception is loc, which DOES include start:stop 
sp500.loc['20130930':'20131007'] # loc will locate, using the index

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
2013-10-07,1687.150024,1687.150024,1674.699951,1676.119995,1676.119995,2678490000

In [30]:
# We may choose to show just some columns
sp500['High']
sp500[ ['Volume', 'High'] ]

                Volume         High
Date
2013-09-30  3308630000  1687.260010
2013-10-01  3238690000  1696.550049
2013-10-02  3148600000  1693.869995
2013-10-03  3279650000  1692.349976
2013-10-04  2880270000  1691.939941
...                ...          ...
2018-09-24  3372210000  2923.790039
2018-09-25  3285480000  2923.949951
2018-09-26  3388620000  2931.149902
2018-09-27  3060850000  2927.219971
2018-09-28  3432300000  2920.530029

[1260 rows x 2 columns]

In [35]:
# using loc and solumn slices together
sp500.loc['20130930':'20131007'][['Open','Close']].mean()

Open     1686.643351
Close    1685.950012
dtype: float64

### Sorting, Filtering and Calculating new columns

In [42]:
# filtered data
sp500.sort_values( ['Volume', 'Close'], ascending=True )

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2013-12-24,1828.020020,1833.319946,1828.020020,1833.319946,1833.319946,1307630000
2017-11-24,2600.419922,2604.209961,2600.419922,2602.419922,2602.419922,1349780000
2015-12-24,2063.520020,2067.360107,2058.729980,2060.989990,2060.989990,1411860000
2014-12-24,2083.250000,2087.560059,2081.860107,2081.879883,2081.879883,1416980000
2015-11-27,2088.820068,2093.290039,2084.129883,2090.110107,2090.110107,1466840000
...,...,...,...,...,...,...
2014-12-19,2061.040039,2077.850098,2061.030029,2070.649902,2070.649902,6465530000
2016-03-18,2041.160034,2052.360107,2041.160034,2049.580078,2049.580078,6503140000
2015-08-24,1965.150024,1965.150024,1867.010010,1893.209961,1893.209961,6612690000
2015-12-18,2040.810059,2040.810059,2005.329956,2005.550049,2005.550049,6683070000
2016-06-24,2103.810059,2103.810059,2032.569946,2037.410034,2037.410034,7597450000

In [43]:
# NB the sort does not persist unless inplace=True
sp500[ sp500['Close'] > sp500['Open'] ]

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
2013-10-10,1660.880005,1692.560059,1660.880005,1692.560059,1692.560059,3362300000
2013-10-11,1691.089966,1703.439941,1688.520020,1703.199951,1703.199951,2944670000
...,...,...,...,...,...,...
2018-09-18,2890.739990,2911.169922,2890.429932,2904.310059,2904.310059,3074610000
2018-09-19,2906.600098,2912.360107,2903.820068,2907.949951,2907.949951,3280020000
2018-09-20,2919.729980,2934.800049,2919.729980,2930.750000,2930.750000,3337730000
2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000

In [45]:
# log values in a new column
sp500['logClose'] = np.log( sp500['Close'] )
sp500

,Open,High,Low,Close,Adj Close,Volume,logClose
Date,,,,,,,
2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000,7.427471
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000,7.435438
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000,7.434771
2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000,7.425751
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000,7.432780
...,...,...,...,...,...,...,...
2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000,7.979123
2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000,7.977817
2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000,7.974523
2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000,7.977282
2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000,7.977275