### Python with Numpy and Pandas
* Python is very efficient
* Numpy adds arrays
* Pandas adds dataframes

In [1]:
import numpy as np
import pandas as pd

In [2]:
# one-dimensional arrays
a = np.array( [5, 72, 13, 100] )
b = np.array( [2, 5, 10, 30] )

result = np.multiply(a, b)
result

array([  10,  360,  130, 3000])

In [3]:
# matrices
matrix_a = np.array([[1,2],[3,4]])
matrix_b = np.array([[.5,.6],[.7,.8]])

result = matrix_a * matrix_b
result.T # T will transpose the matrix

array([[0.5, 2.1],
       [1.2, 3.2]])

In [4]:
# we may flatten the matrix
result.flatten()

array([0.5, 1.2, 2.1, 3.2])

### Working with Data Structures

In [5]:
# Numpy can generate random values
f = np.random.normal(10, 3, 10**7) # sd 3 mean 10, sample size 8
f
f.mean()
f.max()

np.float64(26.65368137744462)

### Loading External Data

In [6]:
# we may choose to parse the dates
sp500 = pd.read_csv('StockData/sp500.csv', parse_dates=True) #, date_format='%m/%d/%y')
# sp500 = pd.read_csv('https://raw.githubusercontent.com/onionmccabbage/pythonThuFri2026/refs/heads/main/StockData/SP500.csv')
# type(sp500)
# sp500['Date'] = pd.to_datetime( sp500['Date'], format='%m/%d/%y' )
# the date must match the incoming data e.g. '%Y-%m-%d'
sp500

,Date,Open,High,Low,Close,Adj Close,Volume
0,9/30/13,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
1,10/01/13,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2,10/02/13,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
3,10/03/13,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
4,10/04/13,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
...,...,...,...,...,...,...,...
1255,9/24/18,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000
1256,9/25/18,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000
1257,9/26/18,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000
1258,9/27/18,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
1259,9/28/18,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000

In [60]:
sp500.describe()

,Date,Open,High,Low,Close,Adj Close,Volume
count,1260,1260.000000,1260.000000,1260.000000,1260.000000,1260.000000,1.260000e+03
mean,2016-03-30 09:57:42.857142,2208.119022,2217.222041,2198.329731,2208.579183,2208.579183,3.545683e+09
min,2013-09-30 00:00:00,1656.989990,1662.469971,1646.469971,1655.449951,1655.449951,1.307630e+09
25%,2014-12-29 18:00:00,1984.504975,1991.565002,1975.112457,1985.515015,1985.515015,3.154532e+09
50%,2016-03-31 12:00:00,2101.550049,2108.744995,2091.594971,2101.265014,2101.265014,3.448470e+09
75%,2017-06-29 06:00:00,2434.364991,2441.522522,2428.234985,2434.777527,2434.777527,3.821982e+09
max,2018-09-28 00:00:00,2936.760010,2940.909912,2927.110107,2930.750000,2930.750000,7.597450e+09
std,NaN,311.783587,312.018261,311.768926,311.699505,311.699505,6.785854e+08

In [55]:
# we may use slicing to access parts of the data
sp500.iloc[0:12] # iloc means index location

,Date,Open,High,Low,Close,Adj Close,Volume
0,9/30/13,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
1,10/01/13,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2,10/02/13,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
3,10/03/13,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
4,10/04/13,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
5,10/07/13,1687.150024,1687.150024,1674.699951,1676.119995,1676.119995,2678490000
6,10/08/13,1676.219971,1676.790039,1655.030029,1655.449951,1655.449951,3569230000
7,10/09/13,1656.989990,1662.469971,1646.469971,1656.400024,1656.400024,3577840000
8,10/10/13,1660.880005,1692.560059,1660.880005,1692.560059,1692.560059,3362300000
9,10/11/13,1691.089966,1703.439941,1688.520020,1703.199951,1703.199951,2944670000
10,10/14/13,1699.859985,1711.030029,1692.130005,1710.140015,1710.140015,2580580000
11,10/15/13,1709.170044,1711.569946,1695.930054,1698.060059,1698.060059,3327740000

In [63]:
# Dates etc.
sp500.info()

<class 'pandas.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1260 non-null   str
 1   Open       1260 non-null   float64
 2   High       1260 non-null   float64
 3   Low        1260 non-null   float64
 4   Close      1260 non-null   float64
 5   Adj Close  1260 non-null   float64
 6   Volume     1260 non-null   int64
dtypes: float64(5), int64(1), str(1)
memory usage: 78.0 KB